// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package mypackage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamIPRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamIPRequest) Reset()         { *m = StreamIPRequest{} }
func (m *StreamIPRequest) String() string { return proto.CompactTextString(m) }
func (*StreamIPRequest) ProtoMessage()    {}
func (*StreamIPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *StreamIPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamIPRequest.Unmarshal(m, b)
}
func (m *StreamIPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamIPRequest.Marshal(b, m, deterministic)
}
func (m *StreamIPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamIPRequest.Merge(m, src)
}
func (m *StreamIPRequest) XXX_Size() int {
	return xxx_messageInfo_StreamIPRequest.Size(m)
}
func (m *StreamIPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamIPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamIPRequest proto.InternalMessageInfo

type StreamIPResponse struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamIPResponse) Reset()         { *m = StreamIPResponse{} }
func (m *StreamIPResponse) String() string { return proto.CompactTextString(m) }
func (*StreamIPResponse) ProtoMessage()    {}
func (*StreamIPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *StreamIPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamIPResponse.Unmarshal(m, b)
}
func (m *StreamIPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamIPResponse.Marshal(b, m, deterministic)
}
func (m *StreamIPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamIPResponse.Merge(m, src)
}
func (m *StreamIPResponse) XXX_Size() int {
	return xxx_messageInfo_StreamIPResponse.Size(m)
}
func (m *StreamIPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamIPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamIPResponse proto.InternalMessageInfo

func (m *StreamIPResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *StreamIPResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamIPRequest)(nil), "mypackage.StreamIPRequest")
	proto.RegisterType((*StreamIPResponse)(nil), "mypackage.StreamIPResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0xad, 0x2c, 0x48, 0x4c,
	0xce, 0x4e, 0x4c, 0x4f, 0x55, 0x12, 0xe4, 0xe2, 0x0f, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xf5, 0x0c,
	0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe3, 0x12, 0x40, 0x08, 0x15, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x31, 0x65, 0x16, 0x08, 0x09, 0x71, 0xb1, 0x14, 0xe4, 0x17, 0x95, 0x48, 0x30, 0x81, 0x45, 0xc0,
	0x6c, 0xa3, 0x18, 0x2e, 0x5e, 0xcf, 0x00, 0xcf, 0xbc, 0xb4, 0xfc, 0x60, 0x88, 0x65, 0x42, 0xde,
	0x5c, 0x3c, 0x30, 0x83, 0x40, 0xc2, 0x42, 0x52, 0x7a, 0x70, 0x7b, 0xf5, 0xd0, 0x2c, 0x95, 0x92,
	0xc6, 0x2a, 0x07, 0xb1, 0x5d, 0x89, 0xc1, 0x80, 0xd1, 0x49, 0x28, 0x4a, 0x40, 0x1f, 0xec, 0x7a,
	0x7d, 0xb8, 0xc2, 0x24, 0x36, 0xb0, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x79, 0x04, 0xda,
	0x75, 0xdf, 0x00, 0x00, 0x00,
}
